### ISSUE TITLE
theme_nifu() loads extrafont

### ISSUE THREAD

**Issue by henrikkarlstrom** [NIFU-NO/nifutheme#7]
Hver bruk av theme_nifu() scanner ttf-fontmappa etter Calibri-fonten, pakker den ut og forsøker å installere den. Den burde kunne prøve å sette Calibri som font først og bare installere den dersom det gir en feilmelding. @sda030

**Comment by sda030** [comment]
Ja, mistenkte det. Tror det er andre funksjoner i extrafont som er mindre invaderende. Eventuelt ragg, men den fikk jeg ikke til å fungere like enkelt (og den er avhengig av extrafont ++).

**Comment by sda030** [comment]
Det vil jo forøvrig også innebære at et saros-dokument tar en del lengre tid å rendre.
